apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-pass
  namespace: wordpress
spec:
  encryptedData:
    password: AgAZI03fmB0k7+orF0OFfrJ2QVqqxp61JfPGdYGpaBSlkwvYC2DZzUFoLrclitCTxy6scvBfe69f4fPYV2EsuVyWpnIzSH37AWRoCjS/CYZaX/KsZOoTH/dtKzEvnqUnLc3horc6TPP1AJE7CFR0ztEr/sOsEkF/rDc0jRJNcn3KfajNoaubOalk2Z40Xy1d+WPzM5td+G7NMlt158gUC1OMMRincetBH9voLeu2CYD5GIJygaRe4ud0Qo6Ao44Aw9B29AaljrCC0e1JIEPr842xKDDjQDoyHN58g/PWxuBu8yQ+mYwHDXnLv4pJZZ4UQmwjmlfcKt+waDAOIrvCdrAIbxY5yrdJY10l79AlOKB6j9iXJtGsPd/VmQiGaClq1V6UDP1IqfUL7dbgcEg+DcpxFh74PhK2oSU6RnCNoEVz7DjL5v+T9sABvsQjdNn0ZWPwitof9ynC6Lq04bmur3rJHl9hA/DfvkjhKK5rbUcdJL8DUKNLV8NWb88X15kb7HT7iNZ4fBP726FZBvtU24+2MOIO8GbagW0yT0SUOwAdYqT1yxiQS6ORNdCICdN0YI+7F51Oy/NtyKfXoZxG3+coiammO5nnjr/rgRUxRs2arImAZAfawq4jBdaTEOS/GNpYTphtcOoMA2lT9hTpIfwYA4UPLQegk4POVe7MIXrslT1bRYIvwurAm3RIOzQJETPq3X/vwVDbSU4y8J2OXYTLhg==
  template:
    metadata:
      creationTimestamp: null
      name: mysql-pass
      namespace: wordpress
    type: Opaque

