apiVersion: v1
kind: PersistentVolume
metadata:
  name: politeauthority-pv
  labels:
    app.kubernetes.io/instance: politeauthority-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/k8s-data/wordpress/politeauthority.io/
    server: 192.168.50.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: politeauthority-claim
  labels:
    app: politeauthority-io
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: politeauthority-pv
