apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstack
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/private-ops.git'
    path: bookstack
    targetRevision: main
    helm:
      valueFiles:
        - values-colfax.yaml
  sources: []
  destination:
    namespace: q-postgres
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true


