apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graylog
spec:
  project: default
  sources:
    - repoURL: 'git@github.com:Graylog2/graylog-helm.git'
      path: charts/graylog
      targetRevision: main
      helm:
        valueFiles:
          - $values/graylog/graylog-helm/values-colfax.yaml
    - repoURL: 'git@github.com:politeauthority/private-ops.git'
      targetRevision: main
      ref: values
  destination:
    namespace: graylog
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
