apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graylog
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/private-ops.git'
    path: graylog/graylog-helm
    targetRevision: main
    helm:
      valueFiles:
        - values-colfax.yaml
  destination:
    namespace: graylog
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
