apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-gateway
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/private-ops.git'
    path: harbor-gateway/
    targetRevision: main
  destination:
    namespace: harbor
    name: in-cluster
  ignoreDifferences:
    - group: "*"
      kind: "*"
      jsonPointers:
        - /metadata/labels
        - /metadata/annotations
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
