apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- q-media.yaml
- q-postgres.yaml
- q-redis.yaml
- organizr.yaml
- hello-world.yaml
- synapse.yaml
- bookstack.yaml
