apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: organizr
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/clusters.git'
    path: colfax/homelab/organizr
    targetRevision: main
  destination:
    namespace: organizr
    name: in-cluster
  syncPolicy:
    # automated:
    #   prune: true
    syncOptions:
      - CreateNamespace=true
