apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: q-postgres
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/private-ops.git'
    path: q-postgres
    targetRevision: main
  destination:
    namespace: q-postgres
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
