apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synapse
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/private-ops.git'
    path: synapse/
    targetRevision: main
  destination:
    namespace: synapse
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
