apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synapse
spec:
  project: default
  sources:
    - repoURL: 'oci://ghcr.io/element-hq/ess-helm'
      chart: matrix-stack
      targetRevision: 26.3.0
      helm:
        valueFiles:
          - $values/synapse/values-colfax.yaml
    - repoURL: 'git@github.com:politeauthority/private-ops.git'
      targetRevision: main
      ref: values
  destination:
    namespace: synapse
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
