version: '3'
tasks:

  check-k:
    cmds:
      - |
        echo "Checking argocd"
        kustomize build cluster/argocd -o argocd.yaml
        echo "✅ argocd"

        echo "Checking bedrock cert-manager"
        kustomize build cluster/bedrock/cert-manager -o cert-manager.yaml
        echo "✅ bedrock cert-manager"

        echo "Checking github-runners"
        kustomize build cluster/sandbox/github-runners -o github-runners.yaml
        echo "✅ github-runners"

        echo "Checking mosquitto"
        kustomize build cluster/sandbox/mosquitto -o mosquitto.yaml
        echo "✅ mosquitto"
    silent: true

  check-helm:
    cmds:
      - |
        HELM_INSTALL="fluentbit"
        HELM_REPO_NAME="fluent-bit"
        HELM_REPO_URL="https://fluent.github.io/helm-charts"
        HELM_DIR="cluster/bedrock/fluentbit"
        VALUES_FILE="values-colfax.yaml"
        echo "Checking ${HELM_INSTALL}"
        helm repo add ${HELM_REPO_NAME} ${HELM_REPO_URL}
        helm dependency build ${HELM_DIR}
        helm lint $HELM_DIR
        helm template ${HELM_DIR} \
          -f ${HELM_DIR}/values-colfax.yaml > ${HELM_INSTALL}.yaml
        echo "✅ ${HELM_INSTALL}"
        rm ${HELM_INSTALL}.yaml


        HELM_INSTALL="ingress-private"
        HELM_REPO_NAME="ingress-nginx"
        HELM_REPO_URL="https://kubernetes.github.io/ingress-nginx"
        HELM_DIR="cluster/bedrock/ingress/ingress-private"
        VALUES_FILE="values-colfax.yaml"
        echo "Checking ${HELM_INSTALL}"
        helm repo add ${HELM_REPO_NAME} ${HELM_REPO_URL}
        helm dependency build ${HELM_DIR}
        helm lint $HELM_DIR
        helm template ${HELM_DIR} \
          -f ${HELM_DIR}/values-colfax.yaml > ${HELM_INSTALL}.yaml
        echo "✅ ${HELM_INSTALL}"
        rm ${HELM_INSTALL}.yaml

        HELM_INSTALL="ingress-public"
        HELM_REPO_NAME="ingress-nginx"
        HELM_REPO_URL="https://kubernetes.github.io/ingress-nginx"
        HELM_DIR="cluster/bedrock/ingress/ingress-public"
        VALUES_FILE="values-colfax.yaml"
        echo "Checking ${HELM_INSTALL}"
        helm repo add ${HELM_REPO_NAME} ${HELM_REPO_URL}
        helm dependency build ${HELM_DIR}
        helm lint $HELM_DIR
        helm template ${HELM_DIR} \
          -f ${HELM_DIR}/values-colfax.yaml > ${HELM_INSTALL}.yaml
        echo "✅ ${HELM_INSTALL}"
        rm ${HELM_INSTALL}.yaml


        HELM_INSTALL="promeheus-stack"
        HELM_REPO_NAME="kube-prometheus-stack"
        HELM_REPO_URL="https://prometheus-community.github.io/helm-charts"
        HELM_DIR="cluster/bedrock/storage/nfs-client"
        VALUES_FILE="values-colfax.yaml"
        echo "Checking ${HELM_INSTALL}"
        helm repo add ${HELM_REPO_NAME} ${HELM_REPO_URL}
        helm dependency build ${HELM_DIR}
        helm lint $HELM_DIR
        helm template ${HELM_DIR} \
          -f ${HELM_DIR}/values-colfax.yaml > ${HELM_INSTALL}.yaml
        echo "✅ ${HELM_INSTALL}"
        rm ${HELM_INSTALL}.yaml

        HELM_INSTALL="nfs-client"
        HELM_REPO_NAME="nfs-subdir-external-provisioner"
        HELM_REPO_URL="https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/"
        HELM_DIR="cluster/bedrock/storage/nfs-client"
        VALUES_FILE="values-colfax.yaml"
        echo "Checking ${HELM_INSTALL}"
        helm repo add ${HELM_REPO_NAME} ${HELM_REPO_URL}
        helm dependency build ${HELM_DIR}
        helm lint $HELM_DIR
        helm template ${HELM_DIR} \
          -f ${HELM_DIR}/values-colfax.yaml > ${HELM_INSTALL}.yaml
        echo "✅ ${HELM_INSTALL}"
        rm ${HELM_INSTALL}.yaml

        HELM_INSTALL="harbor"
        HELM_REPO_NAME="harbor"
        HELM_REPO_URL="https://helm.goharbor.io/"
        HELM_DIR="cluster/sandbox/harbor/"
        VALUES_FILE="values-colfax.yaml"
        echo "Checking ${HELM_INSTALL}"
        helm repo add ${HELM_REPO_NAME} ${HELM_REPO_URL}
        helm dependency build ${HELM_DIR}
        helm lint $HELM_DIR
        helm template ${HELM_DIR} \
          -f ${HELM_DIR}/values-colfax.yaml > ${HELM_INSTALL}.yaml
        echo "✅ ${HELM_INSTALL}"
        rm ${HELM_INSTALL}.yaml

    silent: true
