version: '3'
tasks:

  check-k:
    cmds:
      - |
        echo "Checking argocd"
        kustomize build cluster/argocd -o argocd.yaml
        echo "✅ argocd"

        echo "Checking bedrock cert-manager"
        kustomize build cluster/bedrock/cert-manager -o cert-manager.yaml
        echo "✅ bedrock cert-manager"

        # echo "Checking bedrock ingress-private"
        # kustomize build cluster/bedrock/ingress/ingress-private -o ingress-private.yaml
        # bedrock ingress-private ✅

    silent: true

  check-helm:
    cmds:
      - |
        echo "Checking bedrock ingress-private"
        helm dependency build cluster/bedrock/ingress/ingress-private
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm lint cluster/bedrock/ingress/ingress-private
        helm template cluster/bedrock/ingress/ingress-private \
          -f cluster/bedrock/ingress/ingress-private/values-colfax.yaml > ingress-private.yaml
        echo "✅ bedrock ingress-private"

        echo "Checking bedrock ingress-public"
        helm dependency build cluster/bedrock/ingress/ingress-public
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm lint cluster/bedrock/ingress/ingress-public
        helm template cluster/bedrock/ingress/ingress-public \
          -f cluster/bedrock/ingress/ingress-public/values-colfax.yaml > ingress-public.yaml
        echo "✅ bedrock ingress-public"

        echo "Checking bedrock monitoring promeheus-stack"
        helm dependency build cluster/bedrock/monitoring/prometheus-stack
        helm repo add kube-prometheus-stack https://prometheus-community.github.io/helm-charts
        helm lint cluster/bedrock/monitoring/prometheus-stack
        helm template cluster/bedrock/monitoring/prometheus-stack \
          -f cluster/bedrock/monitoring/prometheus-stack/values-colfax.yaml > prometheus-stack.yaml
        echo "✅ bedrock monitoring prometheus-stack"

        rm ingress-private.yaml
        rm ingress-public.yaml
        rm prometheus-stack.yaml

    silent: true
