apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mysql-8
  labels:
    app.kubernetes.io/instance: wordpress-mysql-8
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/k8s-data/wordpress/mysql-8
    server: 192.168.50.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mysql-8
  labels:
    app: wordpress-mysql-8
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: wordpress-mysql-8
