{
 "title": "Graylog Overview",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "customer",
    "label": "Customer:",
    "query": {
     "query": "label_values(glc_customer_name)"
    }
   },
   {
    "name": "gl_servers_total",
    "query": {
     "query": "query_result(glc_cluster_GL_servers_total{kubernetes_namespace=\"tenant-${customer}\"})"
    }
   },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"tenant-$customer\",pod=~\"graylog-application.*\"}, pod)"
    }
   },
   { "name": "resolution", "query": "1s, 15s, 30s, 1m, 3m, 5m" },
   { "name": "warning_threshold", "label": "PVC % Used Warning Threshold", "query": "80" }
  ]
 },
 "panels": [
  { "title": "K8s metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total pod CPU Request usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_cpu_usage_seconds_total{namespace=\"graylog\", image!=\"\", pod=~\"graylog.*\"}[$__rate_interval])) / sum by (pod) (kube_pod_container_resource_requests{namespace=\"graylog\", resource=\"cpu\", unit=\"core\", pod=~\"graylog.*\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Total pod RAM request usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod) (container_memory_working_set_bytes{namespace=\"graylog\", image!=\"\", pod=~\"graylog.*\"}) / sum by (pod) (kube_pod_container_resource_requests{namespace=\"graylog\", resource=\"memory\", unit=\"byte\", pod=~\"graylog.*\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Running on",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "group by (pod,node) (kube_pod_info{namespace=\"graylog\", pod=~\"graylog.*\"})",
     "legendFormat": "{{ pod }} is running on {{ node }}"
    }
   ]
  },
  {
   "title": "Resources by container",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max by (namespace, pod, container) (kube_pod_container_resource_requests{namespace=\"graylog\", resource=\"cpu\", unit=\"core\"})) by (container)"
    },
    {
     "expr": "sum(max by (namespace, pod, container) (kube_pod_container_resource_limits{namespace=\"graylog\", resource=\"cpu\", unit=\"core\"})) by (container)"
    },
    {
     "expr": "sum(max by (namespace, pod, container) (kube_pod_container_resource_requests{namespace=\"graylog\", resource=\"memory\"})) by (container)"
    },
    {
     "expr": "sum(max by (namespace, pod, container) (kube_pod_container_resource_limits{namespace=\"graylog\", resource=\"memory\"})) by (container)"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"graylog\", image!=\"\", container!=\"POD\"}[$__rate_interval])) by (container)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"graylog\", image!=\"\", container!=\"POD\"}) by (container)"
    }
   ]
  },
  {
   "title": "Network - Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{namespace=\"graylog\", pod=~\"graylog.*\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_bytes_total{namespace=\"graylog\", pod=~\"graylog.*\"}[$__rate_interval]))",
     "legendFormat": "Transmitted  {{pod}}"
    }
   ]
  },
  {
   "title": "Network - Packets Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_packets_total{namespace=\"graylog\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum(rate(container_network_transmit_packets_total{namespace=\"graylog\", pod=\"$pod\"}[$__rate_interval]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "PVCs Full in 2 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=\"graylog\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=\"graylog\"}[1d], 2 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 5 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=\"graylog\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=\"graylog\"}[1d], 5 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Pending State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=\"graylog\",phase=\"Pending\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "PVCs Full in 7 days - Based on Daily Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(\n  count (\n    (kubelet_volume_stats_available_bytes{namespace=\"graylog\"})\n    and\n    (predict_linear(kubelet_volume_stats_available_bytes{namespace=\"graylog\"}[1d], 7 * 24 * 60 * 60) < 0)\n  )\n)\nor\nvector(0)"
    }
   ]
  },
  {
   "title": "PVCs in Lost State",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count((kube_persistentvolumeclaim_status_phase{namespace=\"graylog\",phase=\"Lost\"}==1)) or vector(0)"
    }
   ]
  },
  {
   "title": "PVCs Above Warning Threshold",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=\"graylog\"} ) and (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=\"graylog\"} )) / (max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes{namespace=\"graylog\"} )) >= (${warning_threshold} / 100)) or vector (0)"
    }
   ]
  },
  {
   "title": "Persistent Volume Claim",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": " sum by (persistentvolumeclaim,namespace,storageclass,volumename) (kube_persistentvolumeclaim_info{namespace=\"graylog\"})"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"graylog\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"graylog\"}/1024/1024/1024)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_available_bytes{namespace=\"graylog\"}/1024/1024/1024)"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_status_phase{namespace=\"graylog\",phase=~\"(Pending|Lost)\"}) by (persistentvolumeclaim) + sum(kube_persistentvolumeclaim_status_phase{namespace=\"graylog\",phase=~\"(Lost)\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"graylog\"}/kubelet_volume_stats_capacity_bytes{namespace=\"graylog\"} * 100)"
    }
   ]
  },
  {
   "title": "All Running PVCs Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes{namespace=\"graylog\"}))",
     "legendFormat": "{{namespace}} ({{persistentvolumeclaim}})"
    }
   ]
  },
  { "title": "JVM metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "JVM memory heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg_over_time(jvm_memory_bytes_used{namespace=\"graylog\",area=\"heap\"}[5m])",
     "legendFormat": "Node: {{ node }} Type: {{type}}"
    }
   ]
  },
  {
   "title": "JVM GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{namespace=\"graylog\"}[5m])",
     "legendFormat": "Node: {{ node }} Type: {{type}}"
    }
   ]
  },
  {
   "title": "JVM threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"graylog\"}",
     "legendFormat": "Node: {{ node }} Type: {{type}}"
    }
   ]
  },
  { "title": "Current Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Message Input Rate",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(gl_input_throughput{namespace=\"graylog\"} [1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Journal Utilization",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) ((gl_journal_size{namespace=\"graylog\"} / gl_journal_size_limit{namespace=\"graylog\"}) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Message Output Rate",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(gl_output_throughput{namespace=\"graylog\"} [1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Input Buffer Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (gl_buffer_usage{namespace=\"graylog\",type=\"input\"} / gl_buffer_size{namespace=\"graylog\",type=\"input\"} * 100) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Process Buffer Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (gl_buffer_usage{namespace=\"graylog\",type=\"process\"} / gl_buffer_size{namespace=\"graylog\",type=\"process\"} * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Output Buffer Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (gl_buffer_usage{namespace=\"graylog\",type=\"output\"} / gl_buffer_size{namespace=\"graylog\",type=\"output\"} * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cluster Status (Application Exporters)",
   "type": "stat",
   "description": "Based on status of relevant application exporter (EG - status of graylog exporter, status of mongo exporter)",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "GL Cluster" },
    { "expr": "vector(0)", "legendFormat": "DB Cluster {{ cluster }}" },
    { "expr": "vector(0)", "legendFormat": "ES Cluster" },
    { "expr": "probe_success{}", "legendFormat": "Web UI" }
   ]
  },
  {
   "title": "Index Archive Status",
   "type": "stat",
   "description": "The number of nominal and actual index archives differs. It means, that that the number of archives, that Graylog Server think it should have, is not the number of archives, that is actually stored in S3.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "Catalog Archives" }
   ]
  },
  {
   "title": "License Status",
   "type": "stat",
   "description": "Based on status of relevant application exporter (EG - status of graylog exporter, status of mongo exporter)",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (gl_license_status{namespace=\"graylog\", status=~\"expiration-upcoming\"})",
     "legendFormat": "GL {{ instance }} License Expiration"
    },
    {
     "expr": "avg (gl_license_status{namespace=\"graylog\", status=~\"expired\"})",
     "legendFormat": "GL {{ instance }} License Expired"
    }
   ]
  },
  {
   "title": "Today's input traffic",
   "type": "stat",
   "description": "The number of nominal and actual index archives differs. It means, that that the number of archives, that Graylog Server think it should have, is not the number of archives, that is actually stored in S3.",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gl_traffic_output{namespace=\"graylog\"} [1d]))",
     "legendFormat": "Cluster Volume last 24h"
    },
    { "expr": "vector(0)", "legendFormat": "License Volume for 24h" }
   ]
  },
  {
   "title": "License usage last 24h in %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 13, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A / $B) * 100", "type": "math" }
   ]
  },
  {
   "title": "Index Set Retention Configuration",
   "type": "stat",
   "description": "Based on value of active graylog index settings generated by script check.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "Default Index" },
    { "expr": "vector(0)", "legendFormat": "Illuminate O365" },
    { "expr": "vector(0)", "legendFormat": "Illuminate Sysmon" },
    { "expr": "vector(0)", "legendFormat": "Illuminate Windows Event" },
    { "expr": "vector(0)", "legendFormat": "Illuminate Windows Security" }
   ]
  },
  {
   "title": "Index Set Replica Configuration",
   "type": "stat",
   "description": "Based on value of active graylog index settings generated by script check.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "Default Index" },
    { "expr": "vector(0)", "legendFormat": "Illuminate O365" },
    { "expr": "vector(0)", "legendFormat": "Illuminate Sysmon" },
    { "expr": "vector(0)", "legendFormat": "Illuminate Windows Event" },
    { "expr": "vector(0)", "legendFormat": "Illuminate Windows Security" }
   ]
  },
  {
   "title": "Servers projected to run out of disk within 8 hours",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(predict_linear(node_filesystem_free_bytes{job=\"node-exporter\"}[2h], 8 * 3600) < 0) * -1"
    }
   ]
  },
  { "title": "Historic Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Daily Input Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(gl_traffic_input{namespace=\"graylog\"} [1d]))",
     "legendFormat": "Cluster Total"
    },
    {
     "expr": "sum by (instance) (increase(gl_traffic_input{namespace=\"graylog\"} [1d]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Daily Output Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(gl_traffic_output{namespace=\"graylog\"} [1d]))",
     "legendFormat": "Cluster Total"
    },
    {
     "expr": "sum by (instance) (increase(gl_traffic_output{namespace=\"graylog\"} [1d]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "15-minute Input Traffic Rate",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(gl_traffic_input{namespace=\"graylog\"} [15m]))",
     "legendFormat": "Cluster Total"
    },
    {
     "expr": "sum by (instance) (increase(gl_traffic_input{namespace=\"graylog\"} [15m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Message Rate Graylog Production",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "rate(gl_output_throughput{namespace=\"graylog\"} [150s]) * -1",
     "legendFormat": "{{ instance }}"
    },
    {
     "expr": "rate(gl_input_throughput{namespace=\"graylog\"} [150s])",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Input Buffer Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (gl_buffer_usage{namespace=\"graylog\",type=\"input\"} / gl_buffer_size{namespace=\"graylog\", type=\"input\"} * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Process Buffer Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (gl_buffer_usage{namespace=\"graylog\",type=\"process\"} / gl_buffer_size{namespace=\"graylog\",type=\"process\"} * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Output Buffer Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (gl_buffer_usage{namespace=\"graylog\",type=\"output\"} / gl_buffer_size{namespace=\"graylog\",type=\"output\"} * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Journal Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) ((gl_journal_size{namespace=\"graylog\"} / \ngl_journal_size_limit{namespace=\"graylog\"}) * 100)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Elasticsearch Output Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(gl_elasticsearch_output_writes_total {namespace=\"graylog\"}[1m]))",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Graylog HTTP API Requests",
   "type": "timeseries",
   "description": "I monitor the \"http_thread_pool\" of a Graylog Server. By default, I have 16 minions to delegate work to. If I have 16 threads running for more than 1-2 minutes, then there is a good chance the Graylog parameter \"http_thread_pool_size=\" needs to be increased. But don't stop there, try to figure out why there suddenly is an increase of HTTP requests to Graylog and/or why all of my minions are taking longer than 1-2 minutes to service requests.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "irate(gl_jersey_http_worker_executor_thread_total{namespace=\"graylog\"}[$__rate_interval])",
     "legendFormat": "{{kubernetes_namespace}} {{instance}} {{name}} {{quantile}} {{type}}"
    }
   ]
  },
  {
   "title": "gl_jersey_http_worker_executor_thread",
   "type": "timeseries",
   "description": "I monitor the \"http_thread_pool\" of a Graylog Server. By default, I have 16 minions to delegate work to. If I have 16 threads running for more than 1-2 minutes, then there is a good chance the Graylog parameter \"http_thread_pool_size=\" needs to be increased. But don't stop there, try to figure out why there suddenly is an increase of HTTP requests to Graylog and/or why all of my minions are taking longer than 1-2 minutes to service requests.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 136 },
   "targets": [
    {
     "expr": "gl_jersey_http_worker_executor_thread{namespace=\"graylog\",type=\"running\"}",
     "legendFormat": "{{kubernetes_namespace}} {{instance}} {{name}} {{quantile}} {{type}}"
    }
   ]
  },
  {
   "title": "gl_jersey_http_worker_duration",
   "type": "timeseries",
   "description": "I monitor how long it takes thread(s) of a Graylog Server's httpThreadPool to complete/service a request. I THINK my units of measurement are per-second, but am not 100% sure. Anyhow, if you see me recording values greater than 60, then you need to investigate to determine what requests I'm servicing to then understand why they're taking so long to service/complete.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 145 },
   "targets": [
    {
     "expr": "gl_jersey_http_worker_duration{namespace=\"graylog\"}",
     "legendFormat": "{{kubernetes_namespace}} {{instance}} {{name}} {{quantile}} {{type}}"
    }
   ]
  },
  { "title": "Field Mappings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 154 } },
  {
   "title": "Index field mappings (TOP 30)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "vector(0)", "legendFormat": "`{{index}}`" }
   ]
  }
 ]
}