{
 "title": "NGINX Gateway Fabric",
 "description": "Sample dashboard for NGINX Gateway Fabric",
 "tags": [ "nginx-gateway-fabric" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "nginx_instance",
    "query": {
     "query": "label_values(nginx_http_connections_total,instance)"
    }
   },
   {
    "name": "ngf_instance",
    "label": "ngf_instance",
    "query": {
     "query": "label_values(nginx_gateway_fabric_event_batch_processing_milliseconds_sum,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "NGF Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{instance=~\"$ngf_instance\"}"
    }
   ]
  },
  {
   "title": "NGINX Status for All",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "up{instance=~\"$nginx_instance\"}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "NGINX Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_http_connection_count_connections{instance=~\"$nginx_instance\", nginx_connections_outcome=\"ACTIVE\"}[1m])",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "irate(nginx_http_connection_count_connections{instance=~\"$nginx_instance\", nginx_connections_outcome=\"READING\"}[1m])",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "irate(nginx_http_connection_count_connections{instance=~\"$nginx_instance\", nginx_connections_outcome=\"WAITING\"}[1m])",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "irate(nginx_http_connection_count_connections{instance=~\"$nginx_instance\", nginx_connections_outcome=\"WRITING\"}[1m])",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "NGINX Processed Connections",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "irate(nginx_http_connections_total{instance=~\"$nginx_instance\", nginx_connections_outcome=\"ACCEPTED\"}[1m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "irate(nginx_http_connections_total{instance=~\"$nginx_instance\", nginx_connections_outcome=\"HANDLED\"}[1m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{instance=~\"$nginx_instance\"}[1m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  }
 ]
}