{
 "title": "Q-Media",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Jellyfin", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Streams",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jellyfin_active_sessions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transcoding",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_transcoding_sessions_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Direct Play",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_direct_play_sessions_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Paused",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jellyfin_paused_sessions_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_library_items_total{type=\"Movie\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Series",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_library_items_total{type=\"Series\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Episodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_library_items_total{type=\"Episode\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jellyfin",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jellyfin_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Sessions",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 5 },
   "targets": [
    { "expr": "jellyfin_session_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Viewer Locations",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 5 },
   "targets": [
    { "expr": "jellyfin_session_geo_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Transcoding Detail",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "jellyfin_transcoding_detail_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Streams",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "targets": [
    { "expr": "jellyfin_active_sessions_total", "legendFormat": "Active" },
    {
     "expr": "jellyfin_transcoding_sessions_total",
     "legendFormat": "Transcoding"
    },
    {
     "expr": "jellyfin_direct_play_sessions_total",
     "legendFormat": "Direct Play"
    },
    { "expr": "jellyfin_paused_sessions_total", "legendFormat": "Paused" }
   ]
  },
  {
   "title": "Playback Progress",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jellyfin_stream_progress_percent",
     "legendFormat": "{{user}} ({{client}})"
    }
   ]
  },
  {
   "title": "Stream Bitrate",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "jellyfin_stream_bitrate_bps", "legendFormat": "{{user}} ({{client}})" }
   ]
  },
  { "title": "Media Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Disk Space Used Total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((sum(node_filesystem_avail_bytes{mountpoint=~\"/mnt/media-.*\"}) * 100) / sum(node_filesystem_size_bytes{mountpoint=~\"/mnt/media-.*\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Free Space",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_avail_bytes{mountpoint=~\"/mnt/media-.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Media Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{device!~'rootfs', mountpoint=~\"/mnt/media-.*\"} * 100) / node_filesystem_size_bytes{device!~'rootfs', mountpoint=~\"/mnt/media-.*\"})",
     "legendFormat": "{{mountpoint}}"
    },
    {
     "expr": "100 - ((sum(node_filesystem_avail_bytes{device!~'rootfs', mountpoint=~\"/mnt/media-.*\"}) * 100) / sum(node_filesystem_size_bytes{device!~'rootfs', mountpoint=~\"/mnt/media-.*\"}))",
     "legendFormat": "Total Cluster Space"
    }
   ]
  },
  {
   "title": "Disk 1",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/media-1\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/mnt/media-1\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk 1 Free",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/media-1\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/media-1\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk 2",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/media-2\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/mnt/media-2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk 2 Free",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/media-2\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/media-2\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk 3",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/media-3\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/mnt/media-3\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk 3 Free",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/media-3\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/media-3\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk 4",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/media-4\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/mnt/media-4\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk 4 Free",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/media-4\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/media-4\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk 5",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/media-5\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/mnt/media-5\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk 5 Free",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/media-5\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/media-5\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk 6",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/mnt/media-6\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/mnt/media-6\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk 6 Free",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint=\"/mnt/media-6\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/mnt/media-6\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Downloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 },
   "collapsed": true,
   "panels": [
    {
     "title": "Downloads — Complete",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sabnzbd_folder_bytes{folder=\"complete\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Downloads — Incomplete",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sabnzbd_folder_bytes{folder=\"incomplete\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Kubernetes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"q-media\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"q-media\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"q-media\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"q-media\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"q-media\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"q-media\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  }
 ]
}