apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crowdsec
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/private-ops.git'
    path: crowdsec
    targetRevision: main
    helm:
      valueFiles:
        - values-colfax.yaml
  destination:
    namespace: crowdsec
    name: in-cluster
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
