apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- argocd.yaml
- cert-manager.yaml
- nfs-client.yaml
- fluentbit.yaml
- gateway-api-crds.yaml
- prometheus-stack.yaml
- blackbox-exporter.yaml
- sealed-secrets.yaml
- metallb.yaml
- traefik-crds.yaml
- traefik.yaml
- traefik-config.yaml
- traefik-private.yaml
- traefik-private-config.yaml
