# NFS Client Zeta
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfsclientzeta
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/colfax-ops.git'
    path: cluster/bedrock/storage/nfs-client
    targetRevision: main
    helm:
      valueFiles:
        - values-zeta.yaml
  sources: []
  destination:
    namespace: nfs-client
    name: in-cluster
  syncPolicy:
    # automated: {}
    syncOptions:
      - CreateNamespace=true
