apiVersion: v2
name: fluent-bit
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: fluent-bit
  repository: https://fluent.github.io/helm-charts
  version: 0.34.0
