# Fluentbit Colfax values
# Parses crio runtime
# Adds Seq as an output

fluent-bit:
  logLevel: info

  ## https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/classic-mode/configuration-file
  config:
    service: |
      [SERVICE]
          Daemon Off
          Flush {{ .Values.flush }}
          Log_Level {{ .Values.logLevel }}
          Parsers_File parsers.conf
          Parsers_File custom_parsers.conf
          HTTP_Server On
          HTTP_Listen 0.0.0.0
          HTTP_Port {{ .Values.metricsPort }}
          Health_Check On

    ## https://docs.fluentbit.io/manual/pipeline/inputs
    inputs: |
      [INPUT]
          Name systemd
          Tag host.*
          Systemd_Filter _SYSTEMD_UNIT=kubelet.service
          Read_From_Tail On

      [INPUT]
          Name tail
          Path /var/log/containers/*.log
          Parser cri
          Tag kube.*
          Mem_Buf_Limit 5MB
          Skip_Long_Lines On
          Key log

    ## https://docs.fluentbit.io/manual/pipeline/filters
    filters: |
      [FILTER]
          Name                    kubernetes
          Match                   kube.*
          Merge_Log_Key           log
          Merge_Log               On
          Keep_Log                Off
          Annotations             Off
          Labels                  Off

      [FILTER]
          Name modify
          Match kube.*
          Add cluster colfax

      [FILTER]
          Name          nest
          Match         kube.*
          Operation     lift
          Nested_under  kubernetes
          Add_prefix    kubernetes_

      # [FILTER]
      #     Name          nest
      #     Match         kube.*
      #     Operation     lift
      #     Nested_under  kubernetes_labels
      #     Add_prefix    kubernetes_labels_


    ## https://docs.fluentbit.io/manual/pipeline/outputs
    outputs: |
      [OUTPUT]
          Name                    gelf
          Match                   kube.*
          Host                    192.168.50.6
          Port                    12201
          Mode                    udp
          Gelf_Short_Message_Key  message
          Gelf_Host_Key           kubernetes_pod_name

      [OUTPUT]
          Name                    stdout
          Match                   kube.*

    ## https://docs.fluentbit.io/manual/pipeline/parsers
    # customParsers: |
    #   [PARSER]
    #       Name        cri
    #       Format      regex
    #       Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<logtag>[^ ]*) (?<message>.*)$
    #       Time_Key    time
    #       Time_Format %Y-%m-%dT%H:%M:%S.%L%z
