cert-manager:
  crds:
    enabled: true
    keep: true
  config:
    enableGatewayAPI: true
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 50
        preference:
          matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - arm64
  webhook:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
  cainjector:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
