apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: githubrunners
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/colfax-ops.git'
    path: cluster/sandbox/github-runners
    targetRevision: gha
  destination:
    namespace: actions-runner-system
    name: in-cluster
<<<<<<< HEAD
  syncPolicy:
=======
  # syncPolicy:
>>>>>>> 6c947e6 (Turning off GHA autosync, switching branches)
  #   automated:
  #     prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
