apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: graylog
spec:
  project: default
  source:
    repoURL: 'https://github.com/politeauthority/colfax-ops.git'
    path: cluster/sandbox/graylog
    targetRevision: graylog
    helm:
      valueFiles:
        - values-colfax.yaml
  destination:
    namespace: graylog
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
