apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
spec:
  project: default
  source:
    repoURL: 'git@github.com:politeauthority/clusters.git'
    path: colfax/sandbox/harbor
    targetRevision: harbor
    helm:
      valueFiles:
        - values-colfax.yaml
  destination:
    namespace: harbor
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
