apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: synapse
spec:
  project: default
  source:
    repoURL: 'https://github.com/politeauthority/private-ops'
    path: synapse/env
    targetRevision: synapse
  destination:
    namespace: synapse
    name: in-cluster
  syncPolicy:
    # automated:
    #   prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
