apiVersion: apps/v1
kind: Deployment
metadata:
  name: rescue-0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rescue-0
  template:
    metadata:
      labels:
        app: rescue-0
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker-0
      containers:
        - name: rescue
          # image: harbor.squid-ink.us/politeauthority/polite-cicd:0.0.7
          image: politeauthority/polite-cicd:0.0.9
          imagePullPolicy: Always
          env:
          - name: PG_DB_USER
            valueFrom:
              secretKeyRef:
                key: pg_user
                name: rescue-secrets
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                key: pg_pass
                name: rescue-secrets
          - name: PG_DB_HOST
            valueFrom:
              secretKeyRef:
                key: pg_host
                name: rescue-secrets
          - name: PG_DB_PORT
            valueFrom:
              secretKeyRef:
                key: pg_port
                name: rescue-secrets
          - name: PG_DB_NAME
            valueFrom:
              secretKeyRef:
                key: pg_name
                name: rescue-secrets
          command:
            - tail
            - -f
            - /dev/null
      imagePullSecrets:
        - name: harbor-registry
