apiVersion: v1
kind: Secret
metadata:
  name: rescue-secrets
type: Opaque
data:
  pg_user: cV9wb3N0Z3Jlcw==
  pg_pass: ZHRjc0pVclpYS3VmS3oz
  pg_host: cS1wb3N0Z3Jlcy1ydy5xLXBvc3RncmVzLnN2Yy5jbHVzdGVyLmxvY2Fs
  pg_port: NTQzMg==
  pg_name: cG9zdGdyZXM=
