
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      securityContext:
        runAsUser: 1002
        runAsGroup: 1003
        fsGroup: 1003
        # fsGroupChangePolicy: "OnRootMismatch"
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        ports:
        - containerPort: 9000
        - containerPort: 9090
        command:
        - /bin/bash
        - -c
        args: 
        - minio server /data --console-address :9090
        env:
        - name: MINIO_API_ROOT_ACCESS
          value: "off"
        volumeMounts:
        - name: minio-storage
          mountPath: /data
      volumes:
      - name: minio-storage
        persistentVolumeClaim:
          claimName: minio-storage
