apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-storage
spec:
  capacity:
    storage: 100G
  volumeMode: Filesystem
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/k8s-data/minio
    server: 192.168.50.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100G
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: minio-storage
