apiVersion: v1
kind: Service
metadata:
  name: minio-api
  labels:
    app: minio
    kubernetes.io/name: "minio"
spec:
  selector:
    app: minio
  ports:
    - port: 80
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-api
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: 60m
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy default-src 'self'";
      more_set_headers "X-Frame-Options: SAMEORIGIN";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Referrer-Policy: no-referrer-when-downgrade";
      more_set_headers "Permissions-Policy: none";
spec:
  ingressClassName: nginx-public
  rules:
    - host: a1.alix.lol
      http:
        paths:
          - backend:
              service:
                name: minio-api
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - a1.alix.lol
      secretName: a1-alix-lol
