apiVersion: v1
kind: Service
metadata:
  name: minio-admin
  labels:
    app: minio
    kubernetes.io/name: "minio"
spec:
  selector:
    app: minio
  ports:
  - name: minio-admin
    port: 80
    targetPort: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-admin
spec:
  ingressClassName: nginx-private
  rules:
  - host: minio.colfax.int
    http:
      paths:
      - backend:
          service:
            name: minio-admin
            port:
              number: 80
        path: /
        pathType: Prefix
