---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-postgres-secret
  namespace: monitoring
spec:
  encryptedData:
    GF_DATABASE_PASSWORD: AgA5E4mueeBDUXiu1lzGyOxsbA4XExdMd5TfMeUgeLRGQWPD6wM9qlgQ6TS8t3NB2Aq8BwuZMKtl/56rA8icDL0vjiewW0iGOUSpCT+TBmmlCWza+1OnCp7eMkCBVHw3PH0rZiCe/x3taiBXQh1kptglZ/iCnW7IVKErKsQsneNqBy4tNwDnzPiDMsTQURAS5eZBkNFK+WA/gU/sTP6uC68nOqe82mwArl0VWPDwIEZptqyd6nsA3ot7V9EecqQmhQzYLV8w+sHYnNmCOtIJlv27j0LSOzoZwilmL3kupA6/UMqaaSaS4Yin99T3vota1FADLiRK/RUMfLTMcdLwI1qXKKfME21caZu8EoLCts/9Sp/FyJpT3WGPXBv06GZC7skZf08t7KiwzXIgR8UQmXcwNqu/Rtm0Qggl7HS+YXqoSf4g9RZUWOy3e975+LHz3JLaLdega8vKJDKdAq48T1uS7e7zsy7khj0EA4JxYz8tTfkpUyGllc2ixnCgINCpaNQBIRtz19TadHnScfkComn2eIszxcT6RkrJ1t2/b+skP8hMl1PNTVMiHOnKUoge3TYk/YqRUpghGTWzg09RIqH+2jo+Z17VSA2pMOThJYFeU4ucOnJz0xncXut9nFjwzU3U9Okxr1fbndcxvXskqkvZSZKNGbChHYSqMLvXUh2GV0ZbB5aYHwc07cWjQvkPpyl+3Fu+5BpsZqF1h98uY3IsrWAl0Xxjns0ZjFa+IeY=
  template:
    metadata:
      name: grafana-postgres-secret
      namespace: monitoring
    type: Opaque
