apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-store
spec:
  capacity:
    storage: 2G
  volumeMode: Filesystem
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/k8s-data/grafana
    server: 192.168.50.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-store
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2G
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: grafana-store
