apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-store
spec:
  capacity:
    storage: 2G
  volumeMode: Filesystem
  storageClassName: nfs-zeta
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/media-1/container-data/grafana
    server: 192.168.50.51
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-store
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2G
  storageClassName: nfs-zeta
  volumeMode: Filesystem
  volumeName: grafana-store
