apiVersion: v2
name: Harbor
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
- name: harbor
  repository: https://helm.goharbor.io/
  version: 1.12.2
