nginx-gateway-fabric:
  nginx:
    replicas: 2
    service:
      type: LoadBalancer
      loadBalancerIP: "192.168.50.80"
      externalTrafficPolicy: Local
  nginxGateway:
    gatewayClassName: nginx-public
    metrics:
      enable: true
      port: 9113
  serviceMonitor:
    enable: true
