apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgBKEVYV2kerVupAbsdJSjnKSK/K0gIq4phP8ZpH4EUN1J1eXwH4kIUo8hhDKP7Z2Bpz1dyUAw+OY8HH4aIohcmUMSt1wb6IEuYSeHmATIlZkoDF9jvN5VHcCuBp6kVco4k2bJzHL4110NORbyhEBn+wh54jlZKSQ+SRURvac/XLLx4NePa9VeRHZRyl40JKxAcvyWpRyyw07WPySKdlEwyX3EVEZxOSfDyiyNYWyX0MU3y1t9Wz9FapYiHKcDTCx5YyufDkOYwCuXZEADss+g+Po0Ggx0c3rV+Moi/HSvFH7NBVhqVRXxg0c0inQ1s3GO2Ebl3GSzz51dRpA8xq4aK40Imun1A3Z/+qeM8teToEQzmqtfXCvWdvNqOiQuWrAAnOj9k+DnzfDmuvFAEf3Dibra0PfCGQhrQL+JytYmAOJ757CjEsGfRPFwPt7GQf6SYAvCJFD9sLVZOWEyVT6x2DDHRObFybmWIMMgZlrQP4Y2OWE72a4QTGWyEUMxT8K2P8FMWvTyASA3K3393EOjp1pSBcHLdW3+vkIqS/1erJxPfFS7qYkKXU468NRZ99YIRB9lVH8bHRtRe0kvnHQe7OqBg3mXenwY0yDu+BMPxokgqMTNHUzng4Ly2n5h9XLhWEw5XH9hAhauoCTJ5YE221XLcc0Ed+WhaUwBc2mgQhpdw+weljez0NgG972uXpOKDv6wlC5VZE8JYDIoSl1/KeorYiehnfboZL1cm8nu9wGbjrlmSOiuRj
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: actions-runner-system
