apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-system
spec:
  encryptedData:
    github_token: AgA/E3eHh4ROYFYySZaGy+61ZNJDuvljaU7ns82nwjEWMeAeqoa7qXPrayg+cXi1GpWSm6OkrFZLr5MtXq41TuZgoYjzXnDa48apIOp544CWy8P9xfYhmcrqIHTnBClVxiDU9VyITNQCShZdxIDUVwhe125kkpw7EHk9UsXHu8e8T/IIVrXSJT9Gn/ulZ17jj9x4mSX5l1Aq+1/ApkkxqNvij4P9K2q0ar3q5qWTv1FgcqbAuKrDHbFQnSPfTyCtz9GK8XOBBkApMmJDeZOE2ixmuxbKUqq5WomToc8Srt/uLXExUuVJMAeo513D1nzBGnLY2vdy8+5S0njw0CjrCBPyNWK1GjPo/fuaKsb7vrb66ry/I0h5a5ReMDWDKk2tpNOkvRruRaVhBkR9RuvLuLn2w+jBRluttBklFJ7zurHhwwL/sXNvweaOciJ/6ePirPU+e9uNNvFbwhmNhiK/800L6jsV6VLk7Yu/4EogdcGrX39/6fSeqYsfvvZNIFrfZNwOyH8xEpYF27c+4rVSGkf95+JUMqqgDBrAFgRewixddNFXtUIDvbVGP/Ad2p42QuVKQqgKnNB+4LznEwRbq5DY0QRHU6iQGzTvt7jfalB0PAtPCZwF3E5DpMhbdNsjUgumr9u9Rb3E4sD8bOWaPNMkNICL1hwP40LJPLCpbP+77ryKNsQ0bTeyimIABA+YKqkyQu15HOJpoqO5KaeIESlj8qxnKQ==
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: actions-runner-system

