all:
  children:
    control-plane:
      hosts:
        control-plane-0.k8s.cluster:
          ansible_host: 192.168.50.60
          ansible_user: ubuntu
    worker-nodes:
      hosts:
        worker-0.k8s.cluster:
          ansible_host: 192.168.50.70
          ansible_user: ubuntu
        worker-1.k8s.cluster:
          ansible_host: 192.168.50.71
          ansible_user: ubuntu
        worker-2.k8s.cluster:
          ansible_host: 192.168.50.72
          ansible_user: ubuntu

