all:
  children:
    control-plane:
      hosts:
        control-plane-0.k8s.cluster:
          ansible_host: 192.168.50.60
          ansible_user: ubuntu
    worker-nodes:
      hosts:
        hoyt-1:
          ansible_host: 192.168.50.79
          ansible_user: ubuntu
        colfax-1:
          ansible_host: 192.168.50.77
          ansible_user: ubuntu
        colfax-2:
          ansible_host: 192.168.50.76
          ansible_user: ubuntu
