apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-drive
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /srv/k8s-data/ollama
    server: 192.168.50.6
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-drive
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
  volumeMode: Filesystem
  volumeName: ollama-drive
