metallb:
  crds:
    enabled: true

  speaker:
    frr:
      enabled: false
    tolerations:
      - key: arm
        operator: Equal
        value: "true"
        effect: NoSchedule
      - key: pi
        operator: Equal
        value: "true"
        effect: NoSchedule
