apiVersion: v2
name: openebs
description: A Helm chart for Kubernetes
type: application
version: 0.0.1
appVersion: 0.0.1

dependencies:
  - name: openebs
    repository: https://openebs.github.io/openebs
    version: 4.1.0
