apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  namespace: actions-runner-system
  name: alix-docs
spec:
  replicas: 2
  template:
    spec:
      repository: politeauthority/alix-docs
