apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: eclipse-mosquitto
        ports:
        - containerPort: 8883
        - containerPort: 9001
        volumeMounts:
        - mountPath: /mosquitto/config/mosquitto.conf
          subPath: mosquitto.conf
          name: config
        # - mountPath: /etc/mosquitto/password_file
        #   name: passwords
        #   readOnly: true

      volumes:
      - name: config
        configMap:
          name: mosquitto-config
      # - name: passwords
      #   secret:
      #     secretName: mosquitto-passwords
      #     items:
      #       - key: passwords.txt
      #         path: password_file